package multivers

type CustomerInvoice struct {
	AccountManager         string               `json:"accountManager,omitempty"`
	AccountManagerID       string               `json:"accountManagerId,omitempty"`
	Messages               []interface{}        `json:"messages,omitempty"`
	AmountCreditSqueeze    float64              `json:"amountCreditSqueeze,omitempty"`
	AmountCreditSqueezeCur float64              `json:"amountCreditSqueezeCur,omitempty"`
	AmountRebate           float64              `json:"amountRebate,omitempty"`
	AmountRebateCur        float64              `json:"amountRebateCur,omitempty"`
	AmountTotal            float64              `json:"amountTotal,omitempty"`
	AmountTotalCur         float64              `json:"amountTotalCur,omitempty"`
	AutoCalculateVat       bool                 `json:"autoCalculateVat,omitempty"`
	BordereauxNumber       string               `json:"bordereauxNumber,omitempty"`
	CanChange              bool                 `json:"canChange,omitempty"`
	CannotChangeReason     string               `json:"cannotChangeReason,omitempty"`
	ContactPerson          string               `json:"contactPerson,omitempty"`
	ContactPersonID        string               `json:"contactPersonId,omitempty"`
	CurrencyID             string               `json:"currencyId,omitempty"`
	CustomerID             string               `json:"customerId,omitempty"`
	CustomerInvoiceLines   CustomerInvoiceLines `json:"customerInvoiceLines"`
	DocumentLink           *struct {
		Messages           []interface{} `json:"messages"`
		CanChange          bool          `json:"canChange"`
		CannotChangeReason string        `json:"cannotChangeReason"`
		DateCreated        string        `json:"dateCreated"`
		Description        string        `json:"description"`
		DocumentLink       string        `json:"documentLink"`
		DocumentType       string        `json:"documentType"`
		LinkCategoryName   string        `json:"linkCategoryName"`
		LinkID             string        `json:"linkId"`
		LinkType           string        `json:"linkType"`
		Reference          string        `json:"reference"`
		Subject            string        `json:"subject"`
	} `json:"documentLink,omitempty"`
	DocumentNumber        int         `json:"documentNumber,omitempty"`
	DunForPayment         bool        `json:"dunForPayment,omitempty"`
	ExchangeRate          float64     `json:"exchangeRate,omitempty"`
	FiscalYear            int         `json:"fiscalYear,omitempty"`
	InDirectDebitBatch    bool        `json:"inDirectDebitBatch,omitempty"`
	InvoiceDate           string      `json:"invoiceDate,omitempty"`
	InvoiceExpirationDate string      `json:"invoiceExpirationDate,omitempty"`
	InvoiceID             string      `json:"invoiceId,omitempty"`
	InvoiceType           int         `json:"invoiceType,omitempty"`
	JournalID             string      `json:"journalId,omitempty"`
	JournalSection        string      `json:"journalSection,omitempty"`
	JournalTransaction    int         `json:"journalTransaction,omitempty"`
	KvcPaymentCondition   bool        `json:"kvcPaymentCondition,omitempty"`
	MandateID             string      `json:"mandateId,omitempty"`
	NumberOfReminders     int         `json:"numberOfReminders,omitempty"`
	OpeningBalance        bool        `json:"openingBalance,omitempty"`
	OrderID               string      `json:"orderId,omitempty"`
	PaymentConditionID    string      `json:"paymentConditionId,omitempty"`
	PaymentID             string      `json:"paymentId,omitempty"`
	PaymentReference      string      `json:"paymentReference,omitempty"`
	PeriodNumber          int         `json:"periodNumber,omitempty"`
	ProcessedBy           string      `json:"processedBy,omitempty"`
	ProcessedByID         string      `json:"processedById,omitempty"`
	RebateExpirationDate  string      `json:"rebateExpirationDate,omitempty"`
	RebatePercentage      float64     `json:"rebatePercentage,omitempty"`
	Reference             string      `json:"reference,omitempty"`
	SystemInvoice         bool        `json:"systemInvoice,omitempty"`
	TotalAmountVatExcl    float64     `json:"totalAmountVatExcl,omitempty"`
	TotalAmountVatExclCur float64     `json:"totalAmountVatExclCur,omitempty"`
	VatAdjusted           bool        `json:"vatAdjusted,omitempty"`
	VatAmount             float64     `json:"vatAmount,omitempty"`
	VatAmountCur          float64     `json:"vatAmountCur,omitempty"`
	VatOnInvoice          bool        `json:"vatOnInvoice,omitempty"`
	VatScenarioID         int         `json:"vatScenarioId,omitempty"`
	VatTransactionLines   interface{} `json:"vatTransactionLines,omitempty"`
}

type CustomerInvoiceLines []CustomerInvoiceLine

type CustomerInvoiceLine struct {
	AccountID                 string      `json:"accountId,omitempty"`
	CostCentreID              string      `json:"costCentreId,omitempty"`
	CostUnitID                string      `json:"costUnitId,omitempty"`
	CreditAmount              float64     `json:"creditAmount,omitempty"`
	CreditAmountCur           float64     `json:"creditAmountCur,omitempty"`
	CurrencyID                string      `json:"currencyId,omitempty"`
	CustomerID                string      `json:"customerId,omitempty"`
	DebitAmount               float64     `json:"debitAmount,omitempty"`
	DebitAmountCur            float64     `json:"debitAmountCur,omitempty"`
	Description               string      `json:"description,omitempty"`
	Document                  string      `json:"document,omitempty"`
	FiscalYear                int         `json:"fiscalYear,omitempty"`
	FixedAssetID              string      `json:"fixedAssetId,omitempty"`
	JournalID                 string      `json:"journalId,omitempty"`
	JournalTransaction        int         `json:"journalTransaction,omitempty"`
	OpeningBalanceTransaction bool        `json:"openingBalanceTransaction,omitempty"`
	PeriodNumber              int         `json:"periodNumber,omitempty"`
	Quantity                  float64     `json:"quantity,omitempty"`
	SupplierID                string      `json:"supplierId,omitempty"`
	TransactionDate           string      `json:"transactionDate,omitempty"`
	VatAdjusted               bool        `json:"vatAdjusted,omitempty"`
	VatAmount                 float64     `json:"vatAmount,omitempty"`
	VatCodeID                 interface{} `json:"vatCodeId,omitempty"`
	VatType                   int         `json:"vatType,omitempty"`
}
